# Generated by Django 2.0.7 on 2018-07-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('zona', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('otros', models.CharField(max_length=200)),
            ],
        ),
    ]
